## Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  summarize_dependencies:
    defaults:
      generate_for:
        - "**/*_module.dart"
        - "**/*_app.dart"
    target: ":summarize_dependencies"
    import: "package:inject_generator/inject_generator.dart"
    builder_factories:
      - "summarizeBuilder"
    build_extensions:
      ".dart":
        - ".inject.summary"
    auto_apply: dependents
  generate_source:
    defaults:
      generate_for:
        - "**/*_app.inject.summary"
    required_inputs:
      - ".inject.summary"
    target: ":generate_source"
    import: "package:inject_generator/inject_generator.dart"
    builder_factories:
      - "generateBuilder"
    build_extensions:
      ".dart":
        - ".inject.dart"
    auto_apply: dependents
    build_to: source
